import csv

# 1. Predefined lists of students per branch
ece = [
    "ABHINAV KUMAR", "ABHINAV SAHARAN", "ABHISHEK RAJPOOT", "ADITI GOYAL", "ADITYA DHIMAN", 
    "ADITYA KAPOOR", "AMAN ΜΕΕΝΑ", "AMAN RAJ", "AMBER MITTAL", "ΑΝΙΚET JHA", "ΑΝΚΙTA KARWASRA", 
    "ANMOL PREET SINGH DEOL", "ANSHITA THAKUR", "ARIJIT DEY", "ARPIT SHARMA", "ARYAN SONI", 
    "ARYAN THAKUR", "ASHISH", "ASTHA RAJPUT", "AYUSH KUMAR", "BAPPI SARDAR", "BHOGINDER", 
    "BHUMIKA RANI", "CHETAN RAWAT", "CHITRAKSH MEHRA", "DAKSH", "DAKSH CHOPRA", 
    "DHANISHTA KOUR", "DHRUVI AGARWAL", "DIKSHANT DOTASARA", "DIVYANSH DIXIT", "DIVYANSHI NEGI", 
    "GANESH KUMAR SHARMA", "GAURAANG KUKAL", "GURWINDER SINGH", "HARMANDIP SINGH", "HARSH JHA", 
    "HARSH KATIYAR", "HARSH KUMAR", "HARSHIT PANNU", "HIMANSHU", "HRIDYESH GUPTA", "HRISIT DAS", 
    "ISHAAN GILL", "JAY MANOJ BHANDARKAR", "KARTIK SHIWACH", "KARUNYA MALHOTRA", "KHUSHI", 
    "KRISHAN RANA", "KRISHNA VERMA", "KRITAGAYA BHATIA", "KUNAL LAKHOTIA", "KUNAL SINGH", 
    "LAKSHYA", "LAVANAY JOSHI", "ΜΑΝ HANS", "MANAS BHARDWAJ", "ΜΑΝAV GUPTA", "ΜΑΝKIRAT KAUR", 
    "ΜΑΝTHAN BHARDWAJ", "MANU YADAV", "MANVI", "MANVINDER SINGH", "MANYA JINDAL", "MAYANK PRATAP SINGH", 
    "MOHIT LAMBORIA", "MOHITPREET SINGH", "ΝΑΙΤΙK SHEKHAWAT", "NAMAN GOTHWAL", "NANDNI", 
    "NAVIN KUMAR", "NEMI GULATI", "NIKHIL", "NIKHIL SINGH", "ΝΙΚΙΤA NIMESH", "NISHANT", 
    "NITIN", "OM KUMAR CHOUDHARY", "PALAK", "PIYUSH KUMAR", "PIYUSH KUMAR AGRAWAL", "PIYUSH PATIDAR", 
    "PRANAV KUMAR", "PRANAV NAUTIYAL", "PRATHAM CHAUDHARY", "PRATHAM RAJ", "PRATIK KUMAR", 
    "PRIKSHIT", "PRINCE AGRAWAL", "PRIYANSHU KUMAR", "PRIYANSHU SHARMA", "PULKIT MISHRA", 
    "PUSHKAR PARASHAR", "RAGHAV SAINI", "RAJVI SHARMA", "RAUSHAN KUMAR", "REMI KUMAR", 
    "RISHABH CHAUDHARY", "RISHAV KUMAR", "RISHU KUMAR", "SAHIJDEEP KAUR", "SAHIL SINGH RAVISH", 
    "SAIHAJVEER SINGH SALLAN", "SAKET SREEVALLABHARAM BHOGARAJU", "SAMRAT SINGH CHOUDHARY", 
    "SANCHIT GARG", "SANCHIT GUPTA", "SANJEET", "SHIKHAR BHARDWAJ", "SHIVAM KUMAR BANSAL", 
    "SHUBHAM KUMAR VERMA", "SHUBHAM SINGH SHAH", "SOMESH MINA", "SONI KUMARI", "SOURAV ARORA", 
    "SRIYUT BHARDWAJ", "SURBHI", "TANISH", "TEJVEER SINGH", "TEJVIR SINGH", "TENZIN LAKSHAY", 
    "TUSHARVIR SINGH", "VAISHNAV NARESH RAJENDRAPRASAD", "VENU GOPAL AUDICHYA", "VHASWAR ROY", 
    "VIDYA SAGAR", "VIKAS KUMAR", "VIMAL JANGIR", "VINAYAK AGARWAL", "VIPUL CHAUDHARY", 
    "VYOM GARG", "YENI"
]

eee = [
    "ABHISHEK", "ADARSH PRIYADARSHI", "ADITYA GAURAV", "AKSHIT", "AMAN KUMAR RAM", 
    "ANANT SIROHI", "ANCHALPREET KAUR LUBANA", "ANKIT KUMAR", "ANKITA KUMARI", "ANSH JAISWAL", 
    "ARPIT", "ARPIT RAJ", "ARUSHI SINGLA", "ASHISH CHOUDHARY", "ATUL MAURYA", "AVINASH YADAV", 
    "AYUSH CHOUBEY", "AYUSH RAJ", "AYUSH RAJAWAT", "AYUSHI JAIN", "BIMALJOT KAUR", "CHANDAN KUMAR SINGH", 
    "DEARDEEP SINGH", "DEEPANSHU RATHORE", "DEVANSH KANSAL", "DIKSHANT", "SAINI", "GANESH BAITHA", 
    "GOPAL", "SINGH", "GURVINDER SINGH", "DIPESH", "GOKUL", "GURKIRAT", "HARJEET SINGH", 
    "HARJOT SINGH BHULLAR", "HARNOOR KAUR MANN", "HARSHIT", "HARSHIT KUMAR", "HARSHITA RAINA", 
    "HEMANG GOTHWAL", "HEMANT KUMAR", "HITESH KUMAR MEENA", "ISHANT", "ISHDEEP KAUR", 
    "JAANSHI", "JASREET SINGH MONGA", "ΚΑΝΙΚΑ", "KARTIK BANSAL", "MAHEEP RANJAN", 
    "ΜΑΝKIRAT SINGH", "MANVEER SINGH NAURA", "MUHAMMED JUNAID BHATI", "ΝΑΜAN KUMAR GUPTA", 
    "NAMAN PATAWAT", "NIHARIKA", "PARTEEK", "PAWANDEEP KAUR", "PRANJAL CHAUHAN", "PRASHANT KUMAR", 
    "PRATHAM THAKUR", "PRATIBHA GANGWAR", "PREM KUMAR CHOUDHARY", "PRINCE KUMAR", "RAJIT ANMOL", 
    "RAKSHIT SHARMA", "RANVIR SHARMA", "RASHMEET SINGH", "RAVTEJ SINGH", "RITIKA", 
    "ROHIT KUMAR", "SANCHIT GARG", "SATYAM BHARDWAJ", "SHANAND KUMAR", "SHIVAM KUMAR", 
    "SHLOK GUPTA", "SHRUTI", "SHUBHAM GUPTA", "SHUBHAM KUMAR SINGH", "SHUBHKARMAN SINGH", 
    "SRISHTI", "SUNITA GARWA", "SURYANSH SINGH CHAUHAN", "SWASTIKA SARKAR", "TANUJ", 
    "TEEKAM MΕΕΝΑ", "UMANG", "VAISHNAVI DWIVEDI", "VANSH", "VANSH CHAWLA", "VIKRAMJEET SINGH", 
    "YASH KIRTI", "ZAHEENJOT KAUR", "ZULFIQAR ALI"
]

it = [
    "AAYUSH", "ABHINAV KUMAR SINHA", "ABHINAV PANDEY", "ADITYA KUMAR SAROJ", "AGASTYA GAUTAM", 
    "AJAY WATTS", "AJIT SINGH", "AKHILESH", "AMAN JANGID", "AMAN SINGH KUNTAL", "ΑΝΙΚΕT GODIYAL", 
    "ANKUSH MAZUMDER", "ANMOL RATAN", "ANSHITA SRIVASTAVA", "ANTRIKSHA MISHRA", "ANUBHAV GAUTAM", 
    "ARAV KHANNA", "ARJUN MITTAL", "ARMANDEEP SINGH BAINS", "ARNAV SINGH", "ARPAN BHATTACHARYA", 
    "ARSHIYA GORSIYA", "ARYAN GARG", "AYUSH KUMAR", "AYUSH SHUKLA", "BHAVYA PAMNANI", 
    "CHAMANPREET SINGH", "CHIRAYU CHOUDHARY", "DEVENDER SINGH", "DHANASHRI PATWAL", "DHERYANSHU", 
    "DHRUV CHAHAL", "DIKSHIT KUMAR", "DIVYANSH GUPTA", "GARVIT SINGLA", "GAURAV VERMA", 
    "GOURAV BHAT", "GUDDU KUMAR", "GULSHAN KUMAR", "HARSHDEEP SINGH LIBRA", "HARSHITA AGGARWAL", 
    "HARSHRAJ", "HIMANSHU MEENA", "HITESH SURA", "ISHANT AGARWAL", "ISHNOORDEEP SINGH", 
    "JASHANDEEP SINGH", "JIGMED DOKID", "KHUSHI GUPTA", "KUMKUM", "KUSHAGRA JAIN", "LAKSHAY GARG", 
    "LAKSHYA JAIN", "LOHITAKSH", "MADHAV SATIJA", "MANAVJOT SINGH PRAGPURI", "MANDEEP SINGH RUHAL", 
    "MANISH KUMAR VERMA", "MANJEET KUMAR", "MAYANK", "MOHIT", "MOHIT RAI", "MOLI KUMARI", 
    "NEETIGYA BISHΝΟΙ", "NIHARIKA", "NIKHIL AGGARWAL", "NIRBHAY SINGH", "PANKAJ KUMAR", 
    "PARAM GAUTAM", "PARAS BANSAL", "PARTEEK BANSAL", "PARTH MITTAL", "PIYUSH KUMAR", 
    "PIYUSH SURAJDEO PORTE", "PRATHAM RATHEE", "PUNEET KUMAR", "PUSHKAR SINGH", "PUSKAR KUMAR RAY", 
    "RANIT DAS", "RIDDHAM DALAL", "RITIK", "ROHAN", "ROHAN GUPTA", "RONAK SINGH", 
    "RUDRANSH AGGARWAL", "SAGAR", "SAKSHAM", "SAKSHAM KHULLAR", "SAKSHAM KUMAR SINGH", 
    "SAMAGRA SAHARIA", "SATYAM HARBOLA", "SATYAM PATEL", "SAURABH MEENA", "SAURAV DHONDIYAL", 
    "SHAURYA ADITYA SINGH THAKUR", "SHAURYA ASHWINI", "SHAZIYA PERWEEN", "SHIVNANDAN SINGH", 
    "SHUBHAM SINGLA", "SONAKSHI JAIN", "SUDHANSHU KUMAR", "SUMEDHA", "SYED FAZEEL RESHAD", 
    "ΤΑΜΑΝΝΑ", "TANISH SINGLA", "TANVIR SINGH", "TARANDEEP SINGH GUJRAL", "TAVISHA JINDAL", 
    "TEJASVA GUPTA", "UTKARSH SINGH", "VANSH GROVER", "VANSH MALIK", "VARUNA", 
    "VED PARTAP SINGH BRAR", "VEDANT GUPTA", "VIBHUTE CHINMAY DATTATRAY", "VISHAV", 
    "YASH CHAUHAN", "YASH KUMAR GUPTA"
]

mech = [
    "ABHINAV BEDI", "ABHISHEK KUMAR", "ADESH SINGH", "AGRIM GUPTA", 
    "AJMEET SINGH", "AMRITANSHU KASHYAP", "ANAND KUMAR YADAV", "ΑΝΙΚΕT KUMAR", "ΑΝΙΚΕT VEDH", 
    "ANKIT KUMAR", "ANSHDEEP SINGH", "ANUSHKA UPADHYAY", "APURBA BISTU", "ARNAV BHATIA", 
    "ARPITA", "ARYAN", "AVINAV TOMAR", "AYUSH MISHRA", "AYUSHI VERMA", "CHOUDHARY HIMESH SHIVRAJ", 
    "DEBJYOTI SINHA", "DEEPANSHU", "DIKSHANT TRIPATHI", "DIWAKAR SINGH", "GURKIRAT SINGH JHANDE", 
    "HAPPY RAI", "HARWINDER SINGH", "HIMANSHU LADDHAR", "HITESH SINGLA", "JASHANPREET KAUR", 
    "JIGYAN GANDHI", "KARANBIR SINGH", "KARTIK SHARMA", "KASHISH VASHISHT", "KAUSTAV CHATTOPADHYAY", 
    "KESHAV RAJ THAKUR", "KRISHNA SINGH", "KUNAL TANWAR", "LUV", "MAKARAND CHOHIL", 
    "MANNAT MAHAJAN", "MANTHAN GUTCH", "MANVEE GARG", "MAYANK", "MD RAIHAN", 
    "MITALI SHARMA", "MONIKA SHEORAN", "MRITUNJAY MISHRA", "NAMAN JAISWAL", "NAVPREET BAJARH", 
    "NEELESH KALIA", "NIKHIL MAAN", "NIKHILESH MALHOTRA", "NIRANJAN KUMAR", "NITESH VERMA", 
    "PARAS", "PARAS SAGAR", "PARTH SARTHI SRIVASTAVA", "PRASHANT KUMAR", "PRASUN PRIYADARSHI", 
    "PRATYUSH SINGH NEGI", "PRIYANSHI", "PUSHP KUMAR", "RAJ SINGH", "RAJIT", 
    "RIYA KUMARI", "ROHANI", "ROHIT", "ROHIT PHOGAT", "SACHIN KUMAR", "SAMRIDHI GUPTA", 
    "SARTHAK SINGH NEGI", "SATVIK GAUR", "SATWIK MAITI", "SAURAV KUMAR", "SHARWAN", 
    "SHIKHAR SHARMA", "SHIVAM DAHIYA", "SHIVANSH NEGI", "SHREYA RANJAN", "SONAM RIGZIN", 
    "SOUMOJIT DUTTA", "SOURAV KUMAR", "SRISHTI", "TACIANO DA ROSA JAIME MARTINS", "TANISH SINGH", 
    "TEJAS DAUN", "VAIDIK TRIVEDI", "VANSHAJ", "VIVEKANAND PATEL"
]

biotech = [
    "AADITYA", "AASHISH", "AAYUSHI SINGLA", "ABHAY KUMAR", "ABHISHEK KUMAR THAKUR", "ADITYA KUMAR", 
    "AGYAPAL SINGH SANDHU", "AMAN KUMAR TIWARI", "ANAYA GOYAL", "ANJALI KUMARI", "ANKIT JINDAL", 
    "ARMAN", "ARYAN RAJ", "ASHISH SINGH BISHT", "AUJASVI DHANESHWAR", "AYUSH GUPTA", 
    "AYUSH KUMAR YADAV", "AYUSH PRAJAPATI", "CHINMAYA JAIN", "DIGVIJAY SINGH", "DISHU", 
    "EKAMPREET SINGH", "GAGANDEEP KAUR", "GURLEEN DHILLON", "GURNOOR SINGH", "HARSHDEEP", 
    "HARSIMRAN SINGH", "HIMANSHU", "IKNOOR SINGH", "ISHITA SAHORE", "ISHMEET KAUR PADHA", 
    "KAMAL DENWAL", "KAVYA KHANNA", "KRISH", "LAKSHYA RAJ KASHYAP", "MANBIR SINGH", 
    "MAYANK SHARMA", "MD SAMIM", "MD SHAYAAN ASLAM", "MEHAK ROHILLA", "NAISHA MISHRA", 
    "NAKUL YADAV", "NAMAN SHARMA", "NIKITA RAWAT", "NIRPAL SINGH", "PARAS", "PARAS SHARMA", 
    "PARTH SARTHI", "POOJA", "PRABAN CHAKMA", "PRABHJEET SINGH", "PRANAV GUPTA", "PRATEEK GOYAL", 
    "PRIYANSHU KUMARI", "PURNIMA MUSHAHARY", "RANBIR SINGH", "RISHAV CHATTOPADHYAY", "RISHI PRASHAR", 
    "ROHIT", "SAKSHAM GOYAL", "SAMBHAV JAIN", "SANJANA GARG", "SANJEEV ANAND OJHA", "SATYAM PANDEY", 
    "SAURABH KUMAR", "SAURAV YADAV", "SHAAN TEJPAL", "SHAVI MAKKAR", "SHLOK SHARMA", "SHUBHAM", 
    "SHUBHDEEP KAUR", "SINGH VAISHNAVI SUJITKUMAR", "SUDHANSHU SAJWAN", "SUHANA SHARMA", 
    "SUNDARAM KUMAR YADAV", "SURYANSH MISHRA", "SUSHMA", "TAJINDER SINGH", "TANMAY BAJAJ", 
    "TWINKLE KHANDELWAL", "VANSH BHARDWAJ", "VANSH GUPTA", "VAYU", "VIVEKANAND", "YASH", "YATI"
]

# Convert lists to sets for fast lookup performance
ece_set = set(ece)
eee_set = set(eee)
it_set = set(it)
mech_set = set(mech)
biotech_set = set(biotech)

def find_branch(student_name):
    """Matches a student's name against branch databases."""
    if not student_name:
        return "UNKNOWN"
    
    clean_name = str(student_name).strip().upper()
    
    if clean_name in ece_set: return "ECE"
    if clean_name in eee_set: return "EEE"
    if clean_name in it_set: return "IT"
    if clean_name in mech_set: return "MECH"
    if clean_name in biotech_set: return "BIOTECH"
    
    return "UNKNOWN"

def process_student_csv(input_csv_path, output_csv_path):
    print(f"Reading input data from: {input_csv_path}")
    
    with open(input_csv_path, mode='r', encoding='utf-8') as infile:
        reader = csv.reader(infile)
        header = next(reader)
        
        # Look for the column containing the student name
        name_col_idx = -1
        for idx, col in enumerate(header):
            if 'name' in col.lower():
                name_col_idx = idx
                break
                
        if name_col_idx == -1:
            print("Error: Could not locate a student name column header in the CSV file!")
            return

        updated_header = header + ["Branch"]
        updated_rows = []
        
        for row in reader:
            if not row: continue  # skip blank rows
            student_name = row[name_col_idx]
            branch = find_branch(student_name)
            
            # Append the calculated branch to the current row array
            updated_rows.append(row + [branch])

    # Save output to the new CSV file
    with open(output_csv_path, mode='w', encoding='utf-8', newline='') as outfile:
        writer = csv.writer(outfile)
        writer.writerow(updated_header)
        writer.writerows(updated_rows)
        
    print(f"Success! Generated output file: {output_csv_path}")

if __name__ == "__main__":
    # Change these filenames to match your local CSV paths
    input_file = "student_details_sorted.csv"
    output_file = "student_details_sorted_with_branches.csv"
    
    process_student_csv(input_file, output_file)